title: Projet

status:
  draft:
    label: Brouillon
  listed:
    label: Publié

tabs:
  intro:
    label: Introduction
    icon: text
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false

              conclusion:
                label: Conclusion
                type: textarea
                buttons: false
                help: Ajouter un court texte après la fiche technique

              youtube:
                label: Lien youtube
                type: url

      - width: 1/3
        sections:
          sidebar:
            type: fields
            fields:
              cover:
                label: Image de couverture
                max: 1
                extends: fields/images

              video:
                extends: fields/images
                max: 1
                label: Vidéo de présentation
                help: Une courte vidéo du projet qui bouclera

              releaseDate:
                label: Date
                type: date

  specs:
    label: Fiche technique
    icon: list-bullet
    fields:
      info:
        type: info
        label: Information
        text: Tous les champs sont optionnels. Si un champs est vide, il ne s'affichera pas dans la page du projet

      category:
        label: Type de projet
        type: select
        options: query
        query: page.parent.categories.split
        width: 1/3
        help: Ajoutez des catégories dans la page "Réalisations"

      artist:
        label: Artiste
        extends: fields/spec

      client:
        label: Client
        extends: fields/spec

      realisator:
        label: Réalisateur
        extends: fields/spec

      productor:
        label: Producteur
        extends: fields/spec

      others:
        type: builder
        label: Autres spécifications techniques
        columns: 3
        fieldsets:
          row:
            name: Spécification technique
            fields:
              title:
                type: text
                label: Titre
              text:
                extends: fields/spec
                width: 1/1

  galery:
    label: Galerie
    icon: image
    fields:
      galery:
        type: files
        label: Galerie
        info: '{{ file.dimensions }}'
        layout: cards
